#!/usr/bin/env python
import sys
import os
import subprocess
import platform
import struct
import importlib
import locale

def get_sys_info():
    """Returns system information as a dict."""

    blob = []

    # get full commit hash
    commit = None
    if os.path.isdir(".git") and os.path.isdir("argopy"):
        try:
            pipe = subprocess.Popen(  # nosec No user provided input to control here
                'git log --format="%H" -n 1'.split(" "),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            so, serr = pipe.communicate()
        except Exception:
            pass
        else:
            if pipe.returncode == 0:
                commit = so
                try:
                    commit = so.decode("utf-8")
                except ValueError:
                    pass
                commit = commit.strip().strip('"')

    blob.append(("commit", commit))

    try:
        (sysname, nodename, release, version_, machine, processor) = platform.uname()
        blob.extend(
            [
                ("python", sys.version),
                ("python-bits", struct.calcsize("P") * 8),
                ("OS", "%s" % (sysname)),
                ("OS-release", "%s" % (release)),
                ("machine", "%s" % (machine)),
                ("processor", "%s" % (processor)),
                ("byteorder", "%s" % sys.byteorder),
                ("LC_ALL", "%s" % os.environ.get("LC_ALL", "None")),
                ("LANG", "%s" % os.environ.get("LANG", "None")),
                ("LOCALE", "%s.%s" % locale.getlocale()),
            ]
        )
    except Exception:
        pass

    return blob


def netcdf_and_hdf5_versions():
    libhdf5_version = None
    libnetcdf_version = None
    try:
        import netCDF4

        libhdf5_version = netCDF4.__hdf5libversion__
        libnetcdf_version = netCDF4.__netcdf4libversion__
    except ImportError:
        try:
            import h5py

            libhdf5_version = h5py.version.hdf5_version
        except ImportError:
            pass
    return [("libhdf5", libhdf5_version), ("libnetcdf", libnetcdf_version)]


def show_versions(file=sys.stdout):  # noqa: C901
    """ Print the versions of argopy and its dependencies

    Parameters
    ----------
    file : file-like, optional
        print to the given file-like object. Defaults to sys.stdout.
    """
    sys_info = get_sys_info()

    try:
        sys_info.extend(netcdf_and_hdf5_versions())
    except Exception as e:
        print(f"Error collecting netcdf / hdf5 version: {e}")

    deps = [
        # (MODULE_NAME, f(mod) -> mod version)
        # In REQUIREMENTS:
        ("argopy", lambda mod: mod.__version__),
        ("xarray", lambda mod: mod.__version__),
        ("scipy", lambda mod: mod.__version__),
        ("sklearn", lambda mod: mod.__version__),
        ("erddapy", lambda mod: mod.__version__),
        ("fsspec", lambda mod: mod.__version__),
        ("aiohttp", lambda mod: mod.__version__),

        ("matplotlib", lambda mod: mod.__version__),
        ("gsw", lambda mod: mod.__version__),
        ("netCDF4", lambda mod: mod.__version__),
        ("dask", lambda mod: mod.__version__),
        # ("toolz", lambda mod: mod.__version__),

        ("pyarrow", lambda mod: mod.__version__),
        ("zarr", lambda mod: mod.__version__),

        ("seaborn", lambda mod: mod.__version__),
        ("IPython", lambda mod: mod.__version__),

        ("bottleneck", lambda mod: mod.__version__),
        ("cartopy", lambda mod: mod.__version__),
        ("cftime", lambda mod: mod.__version__),
        ("conda", lambda mod: mod.__version__),
        ("distributed", lambda mod: mod.__version__),
        ("nc_time_axis", lambda mod: mod.__version__),

        ("numpy", lambda mod: mod.__version__),
        ("pandas", lambda mod: mod.__version__),
        ("packaging", lambda mod: mod.__version__),
        ("pip", lambda mod: mod.__version__),
        ("pytest", lambda mod: mod.__version__),
        ("setuptools", lambda mod: mod.__version__),
        ("sphinx", lambda mod: mod.__version__),

        ("tqdm", lambda mod: mod.__version__),
        ("ipykernel", lambda mod: mod.__version__),
        ("ipywidgets", lambda mod: mod.__version__),
    ]

    deps_blob = list()
    for (modname, ver_f) in deps:
        try:
            if modname in sys.modules:
                mod = sys.modules[modname]
            else:
                mod = importlib.import_module(modname)
        except Exception:
            deps_blob.append((modname, None))
        else:
            try:
                ver = ver_f(mod)
                deps_blob.append((modname, ver))
            except Exception:
                deps_blob.append((modname, "installed"))

    print("\nINSTALLED VERSIONS", file=file)
    print("------------------", file=file)

    for k, stat in sys_info:
        print(f"{k}: {stat}", file=file)

    print("", file=file)
    for k, stat in deps_blob:
        print(f"{k}: {stat}", file=file)

if __name__ == '__main__':
    # sys.path.append(os.path.join(os.path.dirname(__file__), 'helpers'))
    # sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
    # import argopy
    # argopy.show_versions()
    show_versions()

