"""
Tests for the BGC-Argo+ third-party product in argopy. This test page (excluding TestBGCArgoPlusIntegration) has been generated by AI (Claude Sonnet 4.6 model) and reviewed by a human.

These tests cover:
 - :class:`argopy.stores.float.products.bgcargo_plus.BGCArgoPlusStore`
 - The ``'BGCArgoPlus'`` path through :meth:`argopy.ArgoFloat.open_product`

Tests are split into two groups:
 * **Unit tests** (no network)
 * **Integration tests** (network required, they are skipped without an internet connection)

Run::

    pytest argopy/tests/test_stores_float_bgcargoplus.py
"""

import ftplib
import socket
from unittest.mock import MagicMock, patch

import numpy as np
import pytest
import xarray as xr

from argopy.options import PRODUCT_LIST
from argopy.stores.float.products.bgcargo_plus import (
    BGCARGO_PLUS_PAPER_VERSION,
    bgcargo_plus_latest_version,
    bgcargo_plus_versions,
    resolve_bgcargo_plus_version,
    BGCArgoPlusServerError,
    bgcargo_plus_server_available,
    BGCARGO_PLUS_DEFAULT_VERSION,
    BGCARGO_PLUS_FTP_HOST,
    BGCARGO_PLUS_PATH_TEMPLATES,
    BGCArgoPlusStore,
    bgcargo_plus_url,
)
from argopy.tests.helpers.utils import requires_connection


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

TEST_WMO = 6903091
TEST_VERSION = "v0.1_2026_04"
STORE_CLASS = "argopy.stores.float.products.bgcargo_plus.BGCArgoPlusStore"
FTPSTORE_CLASS = "argopy.stores.float.products.bgcargo_plus.ftpstore"

requires_bgcargo_plus_server = pytest.mark.skipif(
    not bgcargo_plus_server_available(), reason="Requires the BGC-Argo+ FTP server"
)


def _mock_fs(store: BGCArgoPlusStore) -> MagicMock:
    """Replace the store FTP file system by a mock, so that no connection is made."""
    store._fs = MagicMock()
    return store._fs


def _make_dummy_dataset() -> xr.Dataset:
    """Return a minimal xarray.Dataset that looks like a BGC-Argo+ file."""
    n = 10
    return xr.Dataset(
        {
            "PRES": ("N_LEVELS", np.linspace(0, 2000, n)),
            "TEMP": ("N_LEVELS", np.random.uniform(2, 25, n)),
            "PSAL": ("N_LEVELS", np.random.uniform(33, 36, n)),
            "DOXY": ("N_LEVELS", np.random.uniform(150, 300, n)),
        },
        attrs={
            "WMO_INST_TYPE": str(TEST_WMO),
            "source": "BGC-Argo+",
            "version": TEST_VERSION,
        },
    )


# ---------------------------------------------------------------------------
# Unit tests — bgcargo_plus_url()
# ---------------------------------------------------------------------------

class TestBGCArgoPlusURL:
    def test_returns_string(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert isinstance(url, str)

    def test_starts_with_ftp(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert url.startswith("ftp://")

    def test_contains_correct_host(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert BGCARGO_PLUS_FTP_HOST in url

    def test_contains_wmo(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert str(TEST_WMO) in url

    def test_contains_default_version(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert BGCARGO_PLUS_DEFAULT_VERSION in url

    def test_custom_version(self):
        custom = "v0.1_2025_12"
        url = bgcargo_plus_url(TEST_WMO, version=custom)
        assert custom in url
        assert BGCARGO_PLUS_DEFAULT_VERSION not in url

    def test_unsupported_version_raises(self):
        with pytest.raises(ValueError, match="Unsupported"):
            bgcargo_plus_url(TEST_WMO, version="v9.9_2099_01")

    def test_ends_with_nc(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert url.endswith(".nc")

    @pytest.mark.parametrize(
        "version, expected",
        [
            ("v0.0_2025_09", f"/outliers_removed/v0.0_2025_09/{TEST_WMO}_Sprof_processed.nc"),
            ("v0.1_2025_12", f"/outliers_removed/v0.1_2025_12/{TEST_WMO}_Sprof_BGCArgoPlus.nc"),
            ("v0.1_2026_04", f"/outliers_removed/v0.1_2026_04/Individual_Floats/{TEST_WMO}_Sprof_BGCArgoPlus.nc"),
            ("v1.0_2026_08", f"/outliers_removed/v1.0_2026_08/Individual_Floats/{TEST_WMO}_Sprof_BGCArgoPlus.nc"),
        ],
    )
    def test_path_per_version(self, version, expected):
        """Each dataset version has its own layout on the FTP server."""
        assert bgcargo_plus_url(TEST_WMO, version=version).endswith(expected)

    def test_default_version_supported(self):
        assert BGCARGO_PLUS_DEFAULT_VERSION in BGCARGO_PLUS_PATH_TEMPLATES


# ---------------------------------------------------------------------------
# Unit tests — BGCArgoPlusStore()
# ---------------------------------------------------------------------------

class TestBGCArgoPlusStoreUnit:
    def test_wmo_stored(self):
        store = BGCArgoPlusStore(TEST_WMO)
        assert store.WMO == TEST_WMO

    def test_wmo_string_accepted(self):
        store = BGCArgoPlusStore(str(TEST_WMO))
        assert store.WMO == TEST_WMO

    def test_default_version(self):
        store = BGCArgoPlusStore(TEST_WMO)
        assert store.version == BGCARGO_PLUS_DEFAULT_VERSION

    def test_custom_version(self):
        store = BGCArgoPlusStore(TEST_WMO, version="v0.1_2025_12")
        assert store.version == "v0.1_2025_12"

    def test_unsupported_version_raises(self):
        with pytest.raises(ValueError, match="Unsupported"):
            BGCArgoPlusStore(TEST_WMO, version="v9.9_2099_01")

    def test_url_property(self):
        store = BGCArgoPlusStore(TEST_WMO)
        assert store.url == bgcargo_plus_url(TEST_WMO)

    def test_repr(self):
        store = BGCArgoPlusStore(TEST_WMO)
        r = repr(store)
        assert str(TEST_WMO) in r
        assert "BGCArgoPlusStore" in r

    def test_open_dataset_mocked(self):
        """open_dataset() should delegate to ftpstore and return a Dataset."""
        dummy_ds = _make_dummy_dataset()
        store = BGCArgoPlusStore(TEST_WMO)

        with patch.object(_mock_fs(store), "open_dataset", return_value=dummy_ds) as mock_od:
            ds = store.open_dataset()
            mock_od.assert_called_once_with(store.url)
            assert isinstance(ds, xr.Dataset)

    def test_open_dataset_extra_kwargs_forwarded(self):
        """Extra kwargs should be passed through to the underlying ftpstore."""
        dummy_ds = _make_dummy_dataset()
        store = BGCArgoPlusStore(TEST_WMO)

        with patch.object(_mock_fs(store), "open_dataset", return_value=dummy_ds) as mock_od:
            store.open_dataset(lazy=True)
            _, call_kwargs = mock_od.call_args
            assert "lazy" in call_kwargs
            assert call_kwargs["lazy"] is True

    def test_open_dataset_file_not_found(self):
        """A FileNotFoundError should be raised when the FTP file is missing."""
        store = BGCArgoPlusStore(TEST_WMO)

        with patch.object(
            _mock_fs(store), "open_dataset", side_effect=FileNotFoundError("550 File not found")
        ):
            with pytest.raises(FileNotFoundError, match=str(TEST_WMO)):
                store.open_dataset()

    def test_invalid_wmo_raises(self):
        """An invalid WMO should raise before any FTP connection is made."""
        with pytest.raises(Exception):  # argopy raises ValueError or similar
            BGCArgoPlusStore(999)  # 999 is not a valid Argo WMO

    def test_bytes_variables_decoded(self):
        """Byte-string variables must be decoded to str, PLATFORM_NUMBER cast to int."""
        raw = xr.Dataset(
            {
                "PLATFORM_NUMBER": ("N_PROF", np.array([b"6903091 ", b"6903091 "])),
                "DATA_MODE": ("N_PROF", np.array([b"D", b"A"])),
            }
        )
        store = BGCArgoPlusStore(TEST_WMO)
        with patch.object(_mock_fs(store), "open_dataset", return_value=raw):
            ds = store.open_dataset()
        assert ds["DATA_MODE"].dtype.kind == "U"
        assert ds["PLATFORM_NUMBER"].dtype.kind == "i"
        assert int(ds["PLATFORM_NUMBER"][0]) == TEST_WMO



# ---------------------------------------------------------------------------
# Unit tests — unreachable server
# ---------------------------------------------------------------------------

class TestBGCArgoPlusServerUnreachable:
    def test_no_connection_at_init(self):
        """Creating a store must not connect to the FTP server."""
        with patch(FTPSTORE_CLASS) as mock_ftpstore:
            store = BGCArgoPlusStore(TEST_WMO)
            assert store.url.startswith("ftp://")
            mock_ftpstore.assert_not_called()

    def test_fs_created_once(self):
        with patch(FTPSTORE_CLASS) as mock_ftpstore:
            store = BGCArgoPlusStore(TEST_WMO)
            assert store.fs is store.fs
            mock_ftpstore.assert_called_once()

    @pytest.mark.parametrize(
        "error",
        [
            ConnectionRefusedError(61, "Connection refused"),
            TimeoutError("timed out"),
            socket.gaierror(8, "nodename nor servname provided"),
            ftplib.error_temp("421 Too many connections"),
        ],
        ids=["refused", "timeout", "dns", "busy"],
    )
    def test_server_error_when_connecting(self, error):
        store = BGCArgoPlusStore(TEST_WMO)
        with patch(FTPSTORE_CLASS, side_effect=error):
            with pytest.raises(BGCArgoPlusServerError, match="Cannot reach the BGC-Argo\\+ server"):
                store.open_dataset()

    def test_server_error_when_fetching(self):
        """The connection may also drop while downloading the file."""
        store = BGCArgoPlusStore(TEST_WMO)
        _mock_fs(store).open_dataset.side_effect = ConnectionResetError(54, "Connection reset by peer")
        with pytest.raises(BGCArgoPlusServerError):
            store.open_dataset()

    def test_server_error_is_an_api_server_error(self):
        from argopy.errors import APIServerError
        assert issubclass(BGCArgoPlusServerError, APIServerError)

    def test_server_error_through_argofloat(self):
        """ArgoFloat.open_product must propagate the explicit server error."""
        from argopy.stores.float.spec import FloatStoreProto

        af = MagicMock(WMO=TEST_WMO, cache=False, cachedir="", timeout=0)
        af.open_product = FloatStoreProto.open_product.__get__(af, type(af))
        with patch(FTPSTORE_CLASS, side_effect=ConnectionRefusedError(61, "Connection refused")):
            with pytest.raises(BGCArgoPlusServerError, match="ftp.soest.hawaii.edu"):
                af.open_product("BGCArgoPlus")

    def test_server_available_checked_lazily(self):
        """Creating a store must not check the server, the check is done once on first access."""
        target = "argopy.stores.float.products.bgcargo_plus.bgcargo_plus_server_available"
        with patch(target, return_value=False) as mock_check:
            store = BGCArgoPlusStore(TEST_WMO)
            mock_check.assert_not_called()
            assert store.server_available is False
            assert store.server_available is False
            mock_check.assert_called_once()
            assert "server available : False" in repr(store)

    @pytest.mark.parametrize("reachable", [True, False])
    def test_server_available(self, reachable):
        target = "argopy.stores.float.products.bgcargo_plus.socket.create_connection"
        side_effect = None if reachable else ConnectionRefusedError(61, "Connection refused")
        with patch(target, side_effect=side_effect) as mock_conn:
            assert bgcargo_plus_server_available(timeout=1) is reachable
            mock_conn.assert_called_once()



# ---------------------------------------------------------------------------
# Unit tests — 'paper' and 'latest' versions
# ---------------------------------------------------------------------------

# What ftpstore.ls returns for the root folder, unsorted, with a non-version entry
SERVER_LISTING = [
    {"name": "/bgc_argo_plus/outliers_removed/v1.0_2026_08", "type": "directory"},
    {"name": "/bgc_argo_plus/outliers_removed/v0.0_2025_09", "type": "directory"},
    {"name": "/bgc_argo_plus/outliers_removed/README.txt", "type": "file"},
    {"name": "/bgc_argo_plus/outliers_removed/v0.1_2026_04", "type": "directory"},
    {"name": "/bgc_argo_plus/outliers_removed/v0.1_2025_12", "type": "directory"},
]


def _mock_server(listing=SERVER_LISTING):
    """Patch the module ftpstore so that listing the server returns ``listing``."""
    return patch(FTPSTORE_CLASS, return_value=MagicMock(ls=MagicMock(return_value=listing)))


class TestBGCArgoPlusVersions:
    def test_paper_version_is_default(self):
        assert BGCARGO_PLUS_PAPER_VERSION == "v0.1_2026_04"
        assert BGCARGO_PLUS_DEFAULT_VERSION == BGCARGO_PLUS_PAPER_VERSION

    def test_versions_sorted_and_filtered(self):
        with _mock_server():
            assert bgcargo_plus_versions() == ["v0.0_2025_09", "v0.1_2025_12", "v0.1_2026_04", "v1.0_2026_08"]

    def test_versions_sorted_numerically(self):
        listing = [{"name": f"/bgc_argo_plus/outliers_removed/{v}"} for v in ["v1.10_2027_01", "v1.2_2026_10"]]
        with _mock_server(listing):
            assert bgcargo_plus_latest_version() == "v1.10_2027_01"

    def test_versions_from_plain_names(self):
        with _mock_server(["v0.1_2026_04", "v1.0_2026_08/"]):
            assert bgcargo_plus_versions() == ["v0.1_2026_04", "v1.0_2026_08"]

    def test_latest_version(self):
        with _mock_server():
            assert bgcargo_plus_latest_version() == "v1.0_2026_08"

    def test_latest_version_empty_server(self):
        with _mock_server([]):
            with pytest.raises(ValueError, match="No BGC-Argo"):
                bgcargo_plus_latest_version()

    def test_versions_server_unreachable(self):
        with patch(FTPSTORE_CLASS, side_effect=ConnectionRefusedError(61, "Connection refused")):
            with pytest.raises(BGCArgoPlusServerError):
                bgcargo_plus_versions()

    def test_resolve(self):
        assert resolve_bgcargo_plus_version("paper") == BGCARGO_PLUS_PAPER_VERSION
        assert resolve_bgcargo_plus_version("v0.1_2025_12") == "v0.1_2025_12"
        with _mock_server():
            assert resolve_bgcargo_plus_version("latest") == "v1.0_2026_08"

    def test_store_paper(self):
        store = BGCArgoPlusStore(TEST_WMO, version="paper")
        assert store.version == BGCARGO_PLUS_PAPER_VERSION
        assert store.requested_version == "paper"

    def test_store_latest_resolved_lazily(self):
        """'latest' must not list the server when the store is created, only on first use, and only once."""
        with _mock_server() as mock_ftpstore:
            store = BGCArgoPlusStore(TEST_WMO, version="latest")
            mock_ftpstore.assert_not_called()
            assert store.version == "v1.0_2026_08"
            assert store.version == "v1.0_2026_08"
            assert mock_ftpstore.call_count == 1
            assert "/v1.0_2026_08/Individual_Floats/" in store.url

    def test_store_latest_unknown_to_module(self):
        """A new release on the server, not yet in BGCARGO_PLUS_PATH_TEMPLATES, must still be usable."""
        listing = SERVER_LISTING + [{"name": "/bgc_argo_plus/outliers_removed/v1.1_2027_02"}]
        with _mock_server(listing):
            store = BGCArgoPlusStore(TEST_WMO, version="latest")
            assert store.url.endswith(f"/v1.1_2027_02/Individual_Floats/{TEST_WMO}_Sprof_BGCArgoPlus.nc")

    def test_url_unknown_version_rejected_by_default(self):
        with pytest.raises(ValueError, match="'paper'"):
            bgcargo_plus_url(TEST_WMO, version="v1.1_2027_02")
        assert "v1.1_2027_02" in bgcargo_plus_url(TEST_WMO, version="v1.1_2027_02", check=False)

    def test_url_paper(self):
        assert bgcargo_plus_url(TEST_WMO, version="paper") == bgcargo_plus_url(TEST_WMO, version=BGCARGO_PLUS_PAPER_VERSION)

    def test_open_product_latest(self):
        """ArgoFloat.open_product must forward version='latest' to the store."""
        from argopy.stores.float.spec import FloatStoreProto

        af = MagicMock(WMO=TEST_WMO, cache=False, cachedir="", timeout=0)
        af.open_product = FloatStoreProto.open_product.__get__(af, type(af))
        mock_store_cls = MagicMock(return_value=MagicMock(open_dataset=MagicMock(return_value=_make_dummy_dataset())))
        with patch(STORE_CLASS, mock_store_cls):
            af.open_product("BGCArgoPlus", version="latest")
            assert mock_store_cls.call_args[1]["version"] == "latest"


# ---------------------------------------------------------------------------
# Unit tests — ArgoFloat.open_product('BGCArgoPlus') integration point
# ---------------------------------------------------------------------------

class TestArgoFloatOpenProductBGCArgoPlus:
    """Test that ArgoFloat.open_product routes 'BGCArgoPlus' correctly."""

    def _make_mock_argofloat(self, wmo=TEST_WMO):
        """Return a minimal ArgoFloat-like mock that exposes the real open_product method."""
        from argopy.stores.float.spec import FloatStoreProto

        af = MagicMock()
        af.WMO = wmo
        af.cache = False
        af.cachedir = ""
        af.timeout = 0
        af.open_product = FloatStoreProto.open_product.__get__(af, type(af))
        af.open_dataset = FloatStoreProto.open_dataset.__get__(af, type(af))
        af.ls_datasets = MagicMock(return_value={"prof": "dummy/6903091_prof.nc"})
        return af

    def test_registered_in_product_list(self):
        assert "BGCArgoPlus" in PRODUCT_LIST.argofloat

    def test_open_product_returns_dataset(self):
        dummy_ds = _make_dummy_dataset()
        af = self._make_mock_argofloat()

        with patch(
            STORE_CLASS,
            return_value=MagicMock(open_dataset=MagicMock(return_value=dummy_ds)),
        ):
            ds = af.open_product("BGCArgoPlus")
            assert isinstance(ds, xr.Dataset)

    def test_version_kwarg_forwarded(self):
        """version kwarg must reach BGCArgoPlusStore constructor."""
        dummy_ds = _make_dummy_dataset()
        af = self._make_mock_argofloat()
        custom_version = "v0.1_2025_12"
        mock_store_cls = MagicMock(
            return_value=MagicMock(open_dataset=MagicMock(return_value=dummy_ds))
        )

        with patch(STORE_CLASS, mock_store_cls):
            af.open_product("BGCArgoPlus", version=custom_version)
            call_kwargs = mock_store_cls.call_args[1]
            assert call_kwargs.get("version") == custom_version

    def test_default_version_used(self):
        dummy_ds = _make_dummy_dataset()
        af = self._make_mock_argofloat()
        mock_store_cls = MagicMock(
            return_value=MagicMock(open_dataset=MagicMock(return_value=dummy_ds))
        )

        with patch(STORE_CLASS, mock_store_cls):
            af.open_product("BGCArgoPlus")
            assert mock_store_cls.call_args[1].get("version") == BGCARGO_PLUS_DEFAULT_VERSION

    def test_unknown_product_raises(self):
        af = self._make_mock_argofloat()
        with pytest.raises(NotImplementedError):
            af.open_product("UnknownProduct")

    def test_open_dataset_rejects_product(self):
        """Third-party products must not be reachable through the official open_dataset facade."""
        af = self._make_mock_argofloat()
        with pytest.raises(ValueError):
            af.open_dataset("BGCArgoPlus")


# ---------------------------------------------------------------------------
# Integration tests (network required)
# ---------------------------------------------------------------------------

@requires_connection
@requires_bgcargo_plus_server
class TestBGCArgoPlusIntegration:
    """Live FTP tests, skipped without an internet connection or if the BGC-Argo+ server is down."""

    def test_url_reachable(self):
        """The SOEST FTP should serve a file for a known BGC float."""
        import fsspec
        url = bgcargo_plus_url(TEST_WMO)
        fs = fsspec.filesystem("ftp", host=BGCARGO_PLUS_FTP_HOST)
        path = url.replace(f"ftp://{BGCARGO_PLUS_FTP_HOST}", "")
        assert fs.exists(path), f"BGC-Argo+ file not found: {url}"

    def test_open_dataset_returns_xarray(self):
        store = BGCArgoPlusStore(TEST_WMO)
        ds = store.open_dataset()
        assert isinstance(ds, xr.Dataset)

    def test_dataset_has_pressure(self):
        store = BGCArgoPlusStore(TEST_WMO)
        ds = store.open_dataset()
        assert "PRES" in ds or any("PRES" in v.upper() for v in ds.data_vars)

    def test_latest_version_on_server(self):
        versions = bgcargo_plus_versions()
        assert BGCARGO_PLUS_PAPER_VERSION in versions
        assert bgcargo_plus_latest_version() == versions[-1]

    def test_argofloat_open_product_latest(self):
        from argopy import ArgoFloat
        ds = ArgoFloat(TEST_WMO).open_product("BGCArgoPlus", version="latest")
        assert isinstance(ds, xr.Dataset)

    def test_argofloat_open_product_bgcargo_plus(self):
        from argopy import ArgoFloat
        ds = ArgoFloat(TEST_WMO).open_product("BGCArgoPlus")
        assert isinstance(ds, xr.Dataset)

    def test_profile2point_returns_point_dataset(self):
        """profile2point() should convert the profile dataset to a point cloud."""
        store = BGCArgoPlusStore(TEST_WMO)
        ds = store.open_dataset()
        ds_point = ds.argo.profile2point()
        assert isinstance(ds_point, xr.Dataset)
        assert "N_POINTS" in ds_point.dims
        assert ds_point.sizes["N_POINTS"] > 0

    def test_point2profile_roundtrip(self):
        """profile2point() followed by point2profile() should recover the same
        number of profiles and be free of TypeError from bytes/str mixing."""
        store = BGCArgoPlusStore(TEST_WMO)
        ds = store.open_dataset()
        n_prof_original = ds.sizes["N_PROF"]
        ds_point = ds.argo.profile2point()
        ds_back = ds_point.argo.point2profile()
        assert isinstance(ds_back, xr.Dataset)
        assert "N_PROF" in ds_back.dims
        assert ds_back.sizes["N_PROF"] == n_prof_original
