"""
Tests for the BGC-Argo+ integration in argopy. This test page has been generated by AI.

These tests cover:
 - :class:`argopy.stores.float.bgcargo_plus.BGCArgoPlusStore`
 - The ``'BGCArgoPlus'`` path through :meth:`argopy.ArgoFloat.open_dataset`

Tests are split into two groups:
 * **Unit tests** (no network) — use mocking / monkeypatching.
 * **Integration tests** (network required) — marked with ``pytest.mark.requires_connection``
   and skipped in CI environments that set ``ARGOPY_SKIP_NETWORK_TESTS=1``.

Run only unit tests::

    pytest tests/test_store_bgcargo_plus.py -m "not requires_connection"

Run all (requires internet access to the SOEST FTP)::

    pytest tests/test_store_bgcargo_plus.py
"""

import os
from unittest.mock import MagicMock, patch

import numpy as np
import pytest
import xarray as xr

from argopy.stores.float.bgcargo_plus import (
    BGCARGO_PLUS_DEFAULT_VERSION,
    BGCARGO_PLUS_FTP_HOST,
    BGCArgoPlusStore,
    bgcargo_plus_url,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

TEST_WMO = 6903091
TEST_VERSION = "v0.1_2025_12"

REQUIRES_CONNECTION = pytest.mark.skipif(
    os.environ.get("ARGOPY_SKIP_NETWORK_TESTS", "0") == "1",
    reason="Network tests disabled via ARGOPY_SKIP_NETWORK_TESTS=1",
)


def _make_dummy_dataset() -> xr.Dataset:
    """Return a minimal xarray.Dataset that looks like a BGC-Argo+ file."""
    n = 10
    return xr.Dataset(
        {
            "PRES": ("N_LEVELS", np.linspace(0, 2000, n)),
            "TEMP": ("N_LEVELS", np.random.uniform(2, 25, n)),
            "PSAL": ("N_LEVELS", np.random.uniform(33, 36, n)),
            "DOXY": ("N_LEVELS", np.random.uniform(150, 300, n)),
        },
        attrs={
            "WMO_INST_TYPE": str(TEST_WMO),
            "source": "BGC-Argo+",
            "version": TEST_VERSION,
        },
    )


# ---------------------------------------------------------------------------
# Unit tests — bgcargo_plus_url()
# ---------------------------------------------------------------------------

class TestBGCArgoPlusURL:
    def test_returns_string(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert isinstance(url, str)

    def test_starts_with_ftp(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert url.startswith("ftp://")

    def test_contains_correct_host(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert BGCARGO_PLUS_FTP_HOST in url

    def test_contains_wmo(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert str(TEST_WMO) in url

    def test_contains_default_version(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert BGCARGO_PLUS_DEFAULT_VERSION in url

    def test_custom_version(self):
        custom = "v0.2_2026_01"
        url = bgcargo_plus_url(TEST_WMO, version=custom)
        assert custom in url
        assert BGCARGO_PLUS_DEFAULT_VERSION not in url

    def test_ends_with_nc(self):
        url = bgcargo_plus_url(TEST_WMO)
        assert url.endswith(".nc")

    def test_filename_pattern(self):
        """File should be named ``<WMO>_Sprof_BGCArgoPlus.nc``."""
        url = bgcargo_plus_url(TEST_WMO)
        filename = url.split("/")[-1]
        assert filename == f"{TEST_WMO}_Sprof_BGCArgoPlus.nc"


# ---------------------------------------------------------------------------
# Unit tests — BGCArgoPlusStore()
# ---------------------------------------------------------------------------

class TestBGCArgoPlusStoreUnit:
    def test_wmo_stored(self):
        store = BGCArgoPlusStore(TEST_WMO)
        assert store.WMO == TEST_WMO

    def test_wmo_string_accepted(self):
        store = BGCArgoPlusStore(str(TEST_WMO))
        assert store.WMO == TEST_WMO

    def test_default_version(self):
        store = BGCArgoPlusStore(TEST_WMO)
        assert store.version == BGCARGO_PLUS_DEFAULT_VERSION

    def test_custom_version(self):
        store = BGCArgoPlusStore(TEST_WMO, version="v0.2_2026_01")
        assert store.version == "v0.2_2026_01"

    def test_url_property(self):
        store = BGCArgoPlusStore(TEST_WMO)
        assert store.url == bgcargo_plus_url(TEST_WMO)

    def test_repr(self):
        store = BGCArgoPlusStore(TEST_WMO)
        r = repr(store)
        assert str(TEST_WMO) in r
        assert "BGCArgoPlusStore" in r

    def test_open_dataset_mocked(self):
        """open_dataset() should delegate to ftpstore and return a Dataset."""
        dummy_ds = _make_dummy_dataset()
        store = BGCArgoPlusStore(TEST_WMO)

        with patch.object(store._fs, "open_dataset", return_value=dummy_ds) as mock_od:
            ds = store.open_dataset()
            mock_od.assert_called_once_with(store.url)
            assert isinstance(ds, xr.Dataset)

    def test_open_dataset_extra_kwargs_forwarded(self):
        """Extra kwargs should be passed through to the underlying ftpstore."""
        dummy_ds = _make_dummy_dataset()
        store = BGCArgoPlusStore(TEST_WMO)

        with patch.object(store._fs, "open_dataset", return_value=dummy_ds) as mock_od:
            store.open_dataset(lazy=True)
            _, call_kwargs = mock_od.call_args
            assert "lazy" in call_kwargs
            assert call_kwargs["lazy"] is True

    def test_open_dataset_file_not_found(self):
        """A FileNotFoundError should be raised when the FTP file is missing."""
        store = BGCArgoPlusStore(TEST_WMO)

        with patch.object(
            store._fs, "open_dataset", side_effect=Exception("550 File not found")
        ):
            with pytest.raises(FileNotFoundError, match=str(TEST_WMO)):
                store.open_dataset()

    def test_invalid_wmo_raises(self):
        """An invalid WMO should raise before any FTP connection is made."""
        with pytest.raises(Exception):  # argopy raises ValueError or similar
            BGCArgoPlusStore(999)  # 999 is not a valid Argo WMO


# ---------------------------------------------------------------------------
# Unit tests — ArgoFloat.open_dataset('BGCArgoPlus') integration point
# ---------------------------------------------------------------------------

class TestArgoFloatOpenDatasetBGCArgoPlus:
    """Test that ArgoFloat.open_dataset routes 'BGCArgoPlus' correctly."""

    def _make_mock_argofloat(self, wmo=TEST_WMO):
        """Return a minimal ArgoFloat-like mock that exposes the patched method."""
        from argopy.stores.float.spec import FloatStoreProto

        # Build a lightweight stub that only has the attributes open_dataset needs
        af = MagicMock()
        af.WMO = wmo
        af.cache = False
        af.cachedir = ""
        af.timeout = 0
        af._dataset = {}
        # Bind the real open_dataset from the patched spec
        af.open_dataset = FloatStoreProto.open_dataset.__get__(af, type(af))
        # ls_dataset should not be called for 'BGCArgoPlus'
        af.ls_dataset = MagicMock(side_effect=AssertionError("ls_dataset should not be called for BGCArgoPlus"))
        return af

    def test_bgcargo_plus_key_bypasses_gdac(self):
        """'BGCArgoPlus' must NOT call ls_dataset (GDAC lookup)."""
        dummy_ds = _make_dummy_dataset()
        af = self._make_mock_argofloat()

        with patch(
            "argopy.stores.float.spec.BGCArgoPlusStore",
            return_value=MagicMock(open_dataset=MagicMock(return_value=dummy_ds)),
        ):
            ds = af.open_dataset("BGCArgoPlus")
            assert isinstance(ds, xr.Dataset)
            af.ls_dataset.assert_not_called()

    def test_bgcargo_plus_stored_in_dataset_cache(self):
        """Result should be cached in self._dataset['BGCArgoPlus']."""
        dummy_ds = _make_dummy_dataset()
        af = self._make_mock_argofloat()

        with patch(
            "argopy.stores.float.spec.BGCArgoPlusStore",
            return_value=MagicMock(open_dataset=MagicMock(return_value=dummy_ds)),
        ):
            af.open_dataset("BGCArgoPlus")
            assert "BGCArgoPlus" in af._dataset

    def test_bgcplus_version_kwarg_forwarded(self):
        """bgcplus_version kwarg must reach BGCArgoPlusStore constructor."""
        dummy_ds = _make_dummy_dataset()
        af = self._make_mock_argofloat()
        custom_version = "v0.2_2026_01"
        mock_store_cls = MagicMock(
            return_value=MagicMock(open_dataset=MagicMock(return_value=dummy_ds))
        )

        with patch("argopy.stores.float.spec.BGCArgoPlusStore", mock_store_cls):
            af.open_dataset("BGCArgoPlus", bgcplus_version=custom_version)
            call_kwargs = mock_store_cls.call_args[1]
            assert call_kwargs.get("version") == custom_version

    def test_normal_dataset_unaffected(self):
        """Standard dataset names ('prof', 'Sprof', …) must still go through GDAC."""
        af = self._make_mock_argofloat()
        af.ls_dataset = MagicMock(return_value={"prof": "ftp://dummy/6903091_prof.nc"})

        # just verify ls_dataset is consulted — don't open the file
        datasets = af.ls_dataset()
        assert "prof" in datasets


# ---------------------------------------------------------------------------
# Integration tests (network required)
# ---------------------------------------------------------------------------

@pytest.mark.requires_connection
class TestBGCArgoPlusIntegration:
    """Live FTP tests — skipped unless ARGOPY_SKIP_NETWORK_TESTS != 1."""

    def test_url_reachable(self):
        """The SOEST FTP should serve a file for a known BGC float."""
        import fsspec
        url = bgcargo_plus_url(TEST_WMO)
        fs = fsspec.filesystem("ftp", host=BGCARGO_PLUS_FTP_HOST)
        path = url.replace(f"ftp://{BGCARGO_PLUS_FTP_HOST}", "")
        assert fs.exists(path), f"BGC-Argo+ file not found: {url}"

    def test_open_dataset_returns_xarray(self):
        store = BGCArgoPlusStore(TEST_WMO)
        ds = store.open_dataset()
        assert isinstance(ds, xr.Dataset)

    def test_dataset_has_pressure(self):
        store = BGCArgoPlusStore(TEST_WMO)
        ds = store.open_dataset()
        assert "PRES" in ds or any("PRES" in v.upper() for v in ds.data_vars)

    def test_argofloat_open_dataset_bgcargo_plus(self):
        from argopy import ArgoFloat
        ds = ArgoFloat(TEST_WMO).open_dataset("BGCArgoPlus")
        assert isinstance(ds, xr.Dataset)
