FROM pangeo/pangeo-notebook:2025.07.31
# We recommend using a specific tag above from https://hub.docker.com/r/pangeo/pangeo-notebook/tags
RUN pip install --no-cache-dir cmocean PyCO2SYS git+http://github.com/euroargodev/argopy.git@master