#!/bin/bash
jupyter labextension install @jupyterlab/server-proxy
#jupyter serverextension enable --py nbserverproxy --sys-prefix

jupyter nbextension enable --py widgetsnbextension --sys-prefix

jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension

jupyter serverextension enable --sys-prefix dask_labextension
jupyter lab workspaces import binder/jupyterlab-workspace.json

#EOF
