#!/bin/bash
# A script that can contain simple commands to be
# run at runtime (as an ENTRYPOINT to the docker container)

# Replace DASK_DASHBOARD_URL with the proxy location
sed -i -e "s|DASK_DASHBOARD_URL|/user/${JUPYTERHUB_USER}/proxy/8787|g" binder/simple_workspace.json
# Get the right workspace ID
sed -i -e "s|WORKSPACE_ID|/user/${JUPYTERHUB_USER}/lab|g" binder/simple_workspace.json

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/simple_workspace.json \
  --NotebookApp.base_url=user/${JUPYTERHUB_USER}

exec "$@"
