name: Cancel duplicate runs
on:
  workflow_run:
    workflows: ["tests in DEV env", "tests in minimal FREE env", "tests in FREE env", "tests OS Windows", "CodeQL"]
    types:
      - requested
jobs:
  cancel:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    if: github.repository == 'euroargodev/argopy'
    steps:
    - uses: styfle/cancel-workflow-action@0.10.1
      with:
        workflow_id: ${{ github.event.workflow.id }}