name: Debug libmamba

on:
  workflow_dispatch: # allows you to trigger the workflow run manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:

  core-pinned:
    # CI tests for environments with core requirements in pinned versions
    # All commits must pass this

    name: Core - Pinned - Py${{matrix.python-version}} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      max-parallel: 12
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        experimental: [false]

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "CONDA_ENV_FILE=ci/requirements/py${{matrix.python-version}}-core-pinned.yml" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "LOG_FILE=argopy-tests-Core-Pinned-Py${{matrix.python-version}}-${{matrix.os}}.log" >> $GITHUB_ENV

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.10-0'
          environment-name: argopy-tests
          environment-file: ${{ env.CONDA_ENV_FILE }}
          init-shell: bash
          cache-environment: false
#          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
          create-args: >-
            python=${{matrix.python-version}}

      - name: Install argopy
        run: |
          python -m pip install --no-deps -e .

      - name: Version info
        run: |
          micromamba info
          micromamba list
